### ISSUE TITLE
[Info] - Add ssh-key to multi host server using Ansible

### ISSUE THREAD

**Issue by hungpt2017** [phamthack/research_noted#27]
**Step 1 - Installing Ansible**
```
sudo apt update
sudo apt install ansible
```

**Step 2 - Setting Up the Inventory File**
```
sudo vi /etc/ansible/hosts
```
- Add server host
```
[servers]
server1 ansible_host=203.0.113.111
server2 ansible_host=203.0.113.112
server3 ansible_host=203.0.113.113
```
- Whenever you want to check your inventory, you can run:
```
ansible-inventory --list -y
```

**Step 3 - Testing Connection**
```
ansible all -m ping -u user_name
```

**Step 4 - Ansible Playbook: Deploy the public key to remote hosts**
- Create file `deploy_authorized_keys.yml`
```
---
- hosts: all
  tasks:
  - name: Add public key
    lineinfile:
      path: "/home/user_name/.ssh/authorized_keys"
      line: "{{ pubkey }}"
```
- Run command line
```
ansible-playbook -u user_name deploy_authorized_keys.yml --extra-vars='pubkey="<pubkey>"'
```
